backend:
  name: git-gateway
  branch: main
  site_domain: https://wessleyn.me
  display_url: https://wessleyn.me
  base_url: https://wessleyn.me
  logo_url: https://wessley.me/assets/img/apple-touch-icon.png

media_folder: src/assets/img/projects
public_folder: /assets/img/projects

media_library:
  name: default

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["full-project.njk", "with-analytics.njk", "mobile-app.njk", "client-project.njk"], default: "full-project.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Name", name: "projectName", widget: "string"}
      - {label: "Project Slug", name: "projectSlug", widget: "string"}
      - {label: "Project Summary", name: "projectSummary", widget: "text"}
      - {label: "Project Image", name: "projectImage", widget: "image"}
      - {label: "Project Overview", name: "projectOverview", widget: "markdown"}
      - {label: "Technologies", name: "technologies", widget: "list"}
      - {label: "Features", name: "features", widget: "list"}
      - {label: "Challenges", name: "challenges", widget: "list"}
      - {label: "GitHub URL", name: "githubUrl", widget: "string", required: false}
      - {label: "Demo URL", name: "demoUrl", widget: "string", required: false}
      - {label: "Previous Project", name: "prevProject", widget: "string", required: false}
      - {label: "Next Project", name: "nextProject", widget: "string", required: false}
